{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/LOCALHOST\\SQL2019;AW2014_DWH",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "LOCALHOST\\SQL2019",
            "database": "AW2014_DWH"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "SQL",
          "path": "localhost\\sql2019;AW2014_DWH",
          "Username": "mano",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "DimDate",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DateKey",
            "summarizeBy": "none"
          },
          {
            "name": "DayNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "DayNumberOfYear",
            "summarizeBy": "none"
          },
          {
            "name": "WeekNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "WeekNumberOfYear",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "MonthNumberOfYear",
            "summarizeBy": "none"
          },
          {
            "name": "CalendarQuarter",
            "dataType": "int64",
            "sourceColumn": "CalendarQuarter",
            "summarizeBy": "none"
          },
          {
            "name": "CalendarSemester",
            "dataType": "int64",
            "sourceColumn": "CalendarSemester",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalQuarter",
            "dataType": "int64",
            "sourceColumn": "FiscalQuarter",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalYear",
            "dataType": "int64",
            "sourceColumn": "FiscalYear",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalSemester",
            "dataType": "int64",
            "sourceColumn": "FiscalSemester",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date"
          },
          {
            "name": "Day Of Week",
            "dataType": "int64",
            "sourceColumn": "Day Of Week",
            "summarizeBy": "none"
          },
          {
            "name": "Day Name",
            "dataType": "string",
            "sourceColumn": "Day Name"
          },
          {
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Day",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Month"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Year",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/LOCALHOST\\SQL2019;AW2014_DWH\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimDate,{\"Sales.FactInternetSales(DateKey)\", \"Sales.FactInternetSales(DateKey) 2\", \"Sales.FactInternetSales(DateKey) 3\", \"Sales.FactResellerSales(DateKey)\", \"Sales.FactResellerSales(DateKey) 2\", \"Sales.FactResellerSales(DateKey) 3\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"DayNumberOfWeek\", Int64.Type}, {\"DayNumberOfMonth\", Int64.Type}, {\"DayNumberOfYear\", Int64.Type}, {\"WeekNumberOfYear\", Int64.Type}, {\"MonthNumberOfYear\", Int64.Type}, {\"CalendarQuarter\", Int64.Type}, {\"CalendarYear\", Int64.Type}, {\"CalendarSemester\", Int64.Type}, {\"FiscalQuarter\", Int64.Type}, {\"FiscalYear\", Int64.Type}, {\"FiscalSemester\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"FullDateAlternateKey\", \"Date\"}, {\"DayNumberOfWeek\", \"Day Of Week\"}, {\"EnglishDayNameOfWeek\", \"Day Name\"}, {\"DayNumberOfMonth\", \"Day\"}, {\"EnglishMonthName\", \"Month\"}, {\"CalendarYear\", \"Year\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Year Month Day",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year"
              },
              {
                "name": "Month",
                "ordinal": 1,
                "column": "Month"
              },
              {
                "name": "Day",
                "ordinal": 2,
                "column": "Day"
              }
            ]
          }
        ]
      },
      {
        "name": "Sales DimCurrency",
        "columns": [
          {
            "name": "CurrencyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CurrencyKey",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyAlternateKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CurrencyAlternateKey"
          },
          {
            "name": "Currancy",
            "dataType": "string",
            "sourceColumn": "Currancy"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/LOCALHOST\\SQL2019;AW2014_DWH\",",
                "    Sales_DimCurrency = Source{[Schema=\"Sales\",Item=\"DimCurrency\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(Sales_DimCurrency,{\"Sales.FactInternetSales\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"Name\", \"Currancy\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Sales DimCustomer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "CustoomerAlternateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustoomerAlternateKey",
            "summarizeBy": "none"
          },
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GeographyKey",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "dataCategory": "City"
          },
          {
            "name": "FirstName",
            "dataType": "string",
            "sourceColumn": "FirstName"
          },
          {
            "name": "MiddleName",
            "dataType": "string",
            "sourceColumn": "MiddleName"
          },
          {
            "name": "LastName",
            "dataType": "string",
            "sourceColumn": "LastName"
          },
          {
            "name": "Title",
            "dataType": "string",
            "sourceColumn": "Title"
          },
          {
            "name": "Suffix",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Suffix"
          },
          {
            "name": "EmailAddress",
            "dataType": "string",
            "sourceColumn": "EmailAddress"
          },
          {
            "name": "AddressLine1",
            "dataType": "string",
            "sourceColumn": "AddressLine1"
          },
          {
            "name": "AddressLine2",
            "dataType": "string",
            "sourceColumn": "AddressLine2"
          },
          {
            "name": "PhoneNumber",
            "dataType": "string",
            "sourceColumn": "PhoneNumber"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/LOCALHOST\\SQL2019;AW2014_DWH\",",
                "    Sales_DimCustomer = Source{[Schema=\"Sales\",Item=\"DimCustomer\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(Sales_DimCustomer,null,\"Unknown\",Replacer.ReplaceValue,{\"City\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",null,\"Unknown\",Replacer.ReplaceValue,{\"MiddleName\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",null,\"Unknown\",Replacer.ReplaceValue,{\"AddressLine1\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",null,\"Unknown\",Replacer.ReplaceValue,{\"AddressLine2\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Replaced Value3\",{\"Sales.FactInternetSales\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Sales DimProduct",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductAlternateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductAlternateKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductNumber",
            "dataType": "string",
            "sourceColumn": "ProductNumber"
          },
          {
            "name": "StandardCost",
            "dataType": "decimal",
            "sourceColumn": "StandardCost",
            "summarizeBy": "none"
          },
          {
            "name": "ListPrice",
            "dataType": "decimal",
            "sourceColumn": "ListPrice",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color"
          },
          {
            "name": "Product",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product"
          },
          {
            "name": "Sub Category",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sub Category"
          },
          {
            "name": "Category",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Category"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/LOCALHOST\\SQL2019;AW2014_DWH\",",
                "    Sales_DimProduct = Source{[Schema=\"Sales\",Item=\"DimProduct\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(Sales_DimProduct,null,\"NA\",Replacer.ReplaceValue,{\"Color\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",null,\"NA\",Replacer.ReplaceValue,{\"SubCategoryName\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",null,\"NA\",Replacer.ReplaceValue,{\"CategoryName\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Replaced Value2\",{\"Sales.FactInternetSales\", \"Sales.FactResellerSales\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"Name\", \"Product\"}, {\"SubCategoryName\", \"Sub Category\"}, {\"CategoryName\", \"Category\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Cat SubCat Product",
            "levels": [
              {
                "name": "Category",
                "ordinal": 0,
                "column": "Category"
              },
              {
                "name": "Sub Category",
                "ordinal": 1,
                "column": "Sub Category"
              },
              {
                "name": "Product",
                "ordinal": 2,
                "column": "Product"
              }
            ]
          }
        ]
      },
      {
        "name": "Sales DimReseller",
        "columns": [
          {
            "name": "ResellerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ResellerKey",
            "summarizeBy": "none"
          },
          {
            "name": "ResellerAlternateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ResellerAlternateKey",
            "summarizeBy": "none"
          },
          {
            "name": "Reseller",
            "dataType": "string",
            "sourceColumn": "Reseller"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/LOCALHOST\\SQL2019;AW2014_DWH\",",
                "    Sales_DimReseller = Source{[Schema=\"Sales\",Item=\"DimReseller\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(Sales_DimReseller,{\"Sales.FactResellerSales\", \"YearOpened\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"ResellerName\", \"Reseller\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"ResellerAlternateKey\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Sales FactInternetSales",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "OrderDateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OrderDateKey",
            "summarizeBy": "none"
          },
          {
            "name": "DueDateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DueDateKey",
            "summarizeBy": "none"
          },
          {
            "name": "ShipDateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ShipDateKey",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CurrencyKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SalesTerritoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrderNumber",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "SalesOrderLineNumber",
            "dataType": "int64",
            "sourceColumn": "SalesOrderLineNumber",
            "summarizeBy": "none"
          },
          {
            "name": "OrderQuantity",
            "dataType": "int64",
            "sourceColumn": "OrderQuantity",
            "summarizeBy": "none"
          },
          {
            "name": "UnitPrice",
            "dataType": "decimal",
            "sourceColumn": "UnitPrice",
            "summarizeBy": "none"
          },
          {
            "name": "DiscountAmount",
            "dataType": "double",
            "sourceColumn": "DiscountAmount",
            "summarizeBy": "none"
          },
          {
            "name": "SalesAmount",
            "dataType": "decimal",
            "sourceColumn": "SalesAmount",
            "summarizeBy": "none"
          },
          {
            "name": "TaxAmt",
            "dataType": "decimal",
            "sourceColumn": "TaxAmt",
            "summarizeBy": "none"
          },
          {
            "name": "OrderDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "OrderDate"
          },
          {
            "name": "DueDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "DueDate"
          },
          {
            "name": "ShipDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "ShipDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/LOCALHOST\\SQL2019;AW2014_DWH\",",
                "    Sales_FactInternetSales = Source{[Schema=\"Sales\",Item=\"FactInternetSales\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(Sales_FactInternetSales,{\"Sales.DimCurrency\", \"Sales.DimCustomer\", \"Sales.DimProduct\", \"Sales.DimTerritory\", \"DimDate(DueDateKey)\", \"DimDate(OrderDateKey)\", \"DimDate(ShipDateKey)\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Sales FactResellerSales",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "OrderDateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OrderDateKey",
            "summarizeBy": "none"
          },
          {
            "name": "DueDateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DueDateKey",
            "summarizeBy": "none"
          },
          {
            "name": "ShipDateKey",
            "dataType": "int64",
            "isHidden": true,
            "isNullable": false,
            "sourceColumn": "ShipDateKey",
            "summarizeBy": "none"
          },
          {
            "name": "ResellerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ResellerKey",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CurrencyKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SalesTerritoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrderNumber",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "SalesOrderLineNumber",
            "dataType": "int64",
            "sourceColumn": "SalesOrderLineNumber",
            "summarizeBy": "none"
          },
          {
            "name": "OrderQuantity",
            "dataType": "int64",
            "sourceColumn": "OrderQuantity",
            "summarizeBy": "none"
          },
          {
            "name": "UnitPrice",
            "dataType": "decimal",
            "sourceColumn": "UnitPrice",
            "summarizeBy": "none"
          },
          {
            "name": "DiscountAmount",
            "dataType": "double",
            "sourceColumn": "DiscountAmount",
            "summarizeBy": "none"
          },
          {
            "name": "SalesAmount",
            "dataType": "decimal",
            "sourceColumn": "SalesAmount",
            "summarizeBy": "none"
          },
          {
            "name": "OrderDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "OrderDate"
          },
          {
            "name": "DueDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "DueDate"
          },
          {
            "name": "ShipDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "ShipDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/LOCALHOST\\SQL2019;AW2014_DWH\",",
                "    Sales_FactResellerSales = Source{[Schema=\"Sales\",Item=\"FactResellerSales\"]}[Data]",
                "in",
                "    Sales_FactResellerSales"
              ]
            }
          }
        ]
      },
      {
        "name": "Sales DimTerritory",
        "columns": [
          {
            "name": "TerritoryKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TerritoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "TerritoryAlternateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TerritoryAlternateKey",
            "summarizeBy": "none"
          },
          {
            "name": "Group",
            "dataType": "string",
            "sourceColumn": "Group"
          },
          {
            "name": "Territory",
            "dataType": "string",
            "sourceColumn": "Territory"
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/LOCALHOST\\SQL2019;AW2014_DWH\",",
                "    Sales_DimTerritory = Source{[Schema=\"Sales\",Item=\"DimTerritory\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(Sales_DimTerritory,{\"Sales.FactInternetSales\", \"Sales.FactResellerSales\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"Name\", \"Territory\"}, {\"RegionCode\", \"Region\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "DAX Measures",
        "columns": [
          {
            "name": "Column1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Column1"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "#Internt Orders",
            "expression": " DISTINCTCOUNT('Sales FactInternetSales'[SalesOrderNumber])",
            "formatString": "#,0"
          },
          {
            "name": "#Reseller Orders",
            "expression": "  DISTINCTCOUNT('Sales FactResellerSales'[SalesOrderNumber])",
            "formatString": "#,0"
          },
          {
            "name": "#Internet Order Details",
            "expression": " COUNT('Sales FactInternetSales'[SalesOrderLineNumber])",
            "formatString": "#,0"
          },
          {
            "name": "#Reseller Order Details",
            "expression": " COUNT('Sales FactResellerSales'[SalesOrderLineNumber])",
            "formatString": "#,0"
          },
          {
            "name": "Total Internet Sales",
            "expression": " SUM('Sales FactInternetSales'[SalesAmount])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Total Reseller Sales",
            "expression": " Sum('Sales FactResellerSales'[SalesAmount])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "fc16ab73-33b3-432e-8190-ba3dda6d2966",
        "fromTable": "Sales FactInternetSales",
        "fromColumn": "DueDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "2c8f5c8e-db3e-4af4-a034-afed71db0bb8",
        "fromTable": "Sales FactInternetSales",
        "fromColumn": "ShipDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "bb86c27b-cae4-42bd-8c08-8e3ba73ec8d3",
        "fromTable": "Sales FactResellerSales",
        "fromColumn": "DueDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "8224de0f-7fd5-4730-ab9f-edf3fb4d6395",
        "fromTable": "Sales FactResellerSales",
        "fromColumn": "OrderDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "99ad9558-99ea-4dfb-a1d4-6f4e88b3c73b",
        "fromTable": "Sales FactResellerSales",
        "fromColumn": "ShipDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "f4cec423-19e5-4173-9d7e-ea8bca13aff0",
        "fromTable": "Sales FactInternetSales",
        "fromColumn": "ProductKey",
        "toTable": "Sales DimProduct",
        "toColumn": "ProductKey"
      },
      {
        "name": "365aff27-71a6-4bf7-ac15-3b5c394a96b5",
        "fromTable": "Sales FactInternetSales",
        "fromColumn": "SalesTerritoryKey",
        "toTable": "Sales DimTerritory",
        "toColumn": "TerritoryKey"
      },
      {
        "name": "bca1c01d-7bcf-4511-8770-986e46a90fa8",
        "fromTable": "Sales FactResellerSales",
        "fromColumn": "SalesTerritoryKey",
        "toTable": "Sales DimTerritory",
        "toColumn": "TerritoryKey"
      },
      {
        "name": "81d09114-00b4-4575-8490-4e145a43e942",
        "fromTable": "Sales FactInternetSales",
        "fromColumn": "OrderDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "8ee23e44-5922-4e16-8244-2c55273fe1fc",
        "fromTable": "Sales FactInternetSales",
        "fromColumn": "CurrencyKey",
        "toTable": "Sales DimCurrency",
        "toColumn": "CurrencyKey"
      },
      {
        "name": "856fec16-0514-4632-af16-7e244ad504be",
        "fromTable": "Sales FactInternetSales",
        "fromColumn": "CustomerKey",
        "toTable": "Sales DimCustomer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "f985e954-4532-4663-9974-c29c554126af",
        "fromTable": "Sales FactResellerSales",
        "fromColumn": "ProductKey",
        "toTable": "Sales DimProduct",
        "toColumn": "ProductKey"
      },
      {
        "name": "7af7e0a4-f56f-432f-9c6b-3e9857000659",
        "fromTable": "Sales FactResellerSales",
        "fromColumn": "ResellerKey",
        "toTable": "Sales DimReseller",
        "toColumn": "ResellerKey"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}